[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "msinspect"
version = "0.0.2"
description = "Inspect Measurement Sets gracefully"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "python-casacore", "rich", "textual", "pypdf", "jiveplot"
]

[project.scripts]
msinspect = "msinspect:cli"